// Tailwind 配置 - 统一配置
window.tailwindConfig = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "tertiary": "#adc6ff",
        "inverse-on-surface": "#283044",
        "primary-fixed-dim": "#ddb7ff",
        "surface-container-high": "#222a3d",
        "background": "#0b1326",
        "on-secondary-fixed": "#341100",
        "on-primary": "#490080",
        "outline": "#988d9f",
        "on-primary-fixed-variant": "#6900b3",
        "inverse-primary": "#842bd2",
        "on-tertiary-fixed": "#001a42",
        "secondary-fixed-dim": "#ffb690",
        "on-surface-variant": "#cfc2d6",
        "on-background": "#dae2fd",
        "tertiary-fixed-dim": "#adc6ff",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#4d8eff",
        "primary": "#ddb7ff",
        "on-primary-container": "#400071",
        "surface-bright": "#31394d",
        "surface-container-low": "#131b2e",
        "surface-container-lowest": "#060e20",
        "primary-container": "#b76dff",
        "secondary-fixed": "#ffdbca",
        "surface": "#0b1326",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#783200",
        "tertiary-fixed": "#d8e2ff",
        "secondary": "#ffb690",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-tertiary": "#002e6a",
        "secondary-container": "#ec6a06",
        "on-secondary-container": "#4a1c00",
        "outline-variant": "#4d4354",
        "on-primary-fixed": "#2c0051",
        "surface-tint": "#ddb7ff",
        "surface-container-highest": "#2d3449",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#004395",
        "primary-fixed": "#f0dbff",
        "on-tertiary-container": "#00285d",
        "surface-dim": "#0b1326",
        "surface-container": "#171f33",
        "error": "#ffb4ab",
        "on-secondary": "#552100"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "slot-size": "64px",
        "container-padding": "32px",
        "stack-sm": "8px",
        "gutter": "16px",
        "base": "4px"
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "h2": ["Sora"],
        "h3": ["Sora"],
        "h1": ["Sora"],
        "body-md": ["Hanken Grotesk"],
        "code": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "code": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}]
      }
    },
  },
}